env: mpe

episode_length: 30
num_agents: 2
num_landmarks: 2
scenario_name: 'simple_spread'
episode_limit: 30

learner_log_interval: 20000
log_interval: 20000
runner_log_interval: 20000
t_max: 10050000
test_interval: 20000
test_nepisode: 24
test_greedy: True
